import { ArchiveTable } from '../types';

export const ARCHIVE_TABLES: ArchiveTable[] = [
  {
    tableName: 'orders',
    partitionColumn: 'created_at',
    columns: [
      'id',
      'order_no',
      'user_id',
      'merchant_id',
      'total_amount',
      'discount_amount',
      'pay_amount',
      'status',
      'pay_status',
      'pay_method',
      'pay_time',
      'delivery_status',
      'delivery_time',
      'complete_time',
      'cancel_time',
      'remark',
      'created_at',
      'updated_at',
      'deleted_at',
    ],
  },
  {
    tableName: 'order_items',
    partitionColumn: 'created_at',
    columns: [
      'id',
      'order_id',
      'order_no',
      'product_id',
      'product_name',
      'product_image',
      'sku_id',
      'sku_spec',
      'price',
      'quantity',
      'subtotal',
      'discount_amount',
      'created_at',
      'updated_at',
    ],
  },
  {
    tableName: 'payments',
    partitionColumn: 'created_at',
    columns: [
      'id',
      'payment_no',
      'order_id',
      'order_no',
      'user_id',
      'amount',
      'pay_method',
      'channel',
      'channel_trade_no',
      'status',
      'success_time',
      'notify_time',
      'created_at',
      'updated_at',
    ],
  },
  {
    tableName: 'operation_logs',
    partitionColumn: 'created_at',
    columns: [
      'id',
      'user_id',
      'username',
      'module',
      'action',
      'method',
      'request_params',
      'response_result',
      'ip',
      'user_agent',
      'status',
      'cost_ms',
      'created_at',
    ],
  },
  {
    tableName: 'access_logs',
    partitionColumn: 'created_at',
    columns: [
      'id',
      'user_id',
      'trace_id',
      'uri',
      'method',
      'query_params',
      'request_body',
      'response_code',
      'response_body',
      'ip',
      'user_agent',
      'cost_ms',
      'created_at',
    ],
  },
];

export default ARCHIVE_TABLES;
